apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: joaoferreira
spec:
  selector:
    app: joaoferreira-project
  ports:
    - protocol: TCP
      port: 52035
      targetPort: 52035
      nodePort: 32035
  type: NodePort
