apiVersion: batch/v1
kind: Job
metadata:
  name: ml-container-job
  namespace: joaoferreira
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
        - name: ml-container
          image: joaojoaovf/ml-container:latest
          env:
            - name: DATASET_URL
              value: https://homepages.dcc.ufmg.br/~cunha/hosted/cloudcomp-2023s2-datasets/2023_spotify_ds1.csv
          volumeMounts:
            - mountPath: /frontend
              name: model-storage
      restartPolicy: Never
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: project2-pv2-joaoferreira
