apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-container
  namespace: joaoferreira 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: joaoferreira-project
    spec:
      containers:
        - name: ml-container
          image: joaojoaovf/ml-container:latest
           env:
        - name: DATASET_URL
          value: https://homepages.dcc.ufmg.br/~cunha/hosted/cloudcomp-2023s2-datasets/2023_spotify_ds1.csv
          volumeMounts:
            - mountPath: /app/data
              name: model-storage
      restartPolicy: Never
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: pvc-frontend
  backoffLimit: 4
