apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc-joaoferreira
  namespace: joaoferreira
spec:
  storageClassName: default-storage-joaoferreira-luizagomes
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: luizagomes
  volumeName: project2-pv2-joaoferreira
