apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: joaoferreira
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 52035
      targetPort: 52035
  type: NodePort
  externalTrafficPolicy: Cluster
